import Phaser from 'phaser';
import { SCENE_KEYS, GAME_WIDTH, GAME_HEIGHT } from '../config/constants';
import { listSaves, loadGame, deleteGame, regenerateIntro, SaveListItem } from '../services/ApiClient';

export class MenuScene extends Phaser.Scene {
  private saveListContainer!: Phaser.GameObjects.Container;
  private menuElements: Phaser.GameObjects.GameObject[] = [];
  private showingSaves: boolean = false;

  constructor() {
    super({ key: SCENE_KEYS.MENU });
  }

  create(): void {
    this.showingSaves = false;
    this.menuElements = [];

    this.cameras.main.setBackgroundColor('#000000');

    // Splash poster (top half)
    const poster = this.add.image(GAME_WIDTH / 2, 150, 'splash_poster');
    const posterMaxW = GAME_WIDTH - 40;
    const posterMaxH = 260;
    const scaleX = posterMaxW / poster.width;
    const scaleY = posterMaxH / poster.height;
    const posterScale = Math.min(scaleX, scaleY);
    poster.setScale(posterScale);
    this.menuElements.push(poster);

    // Fade in the poster
    poster.setAlpha(0);
    this.tweens.add({
      targets: poster,
      alpha: 1,
      duration: 600,
      ease: 'Sine.easeIn'
    });

    // Title overlaid on poster
    const title = this.add.text(GAME_WIDTH / 2, 280, 'DUNGEON WEAVER', {
      fontSize: '36px',
      fontFamily: 'monospace',
      color: '#c9a227',
      stroke: '#000000',
      strokeThickness: 6
    }).setOrigin(0.5);
    this.menuElements.push(title);

    // Tagline
    const tagline = this.add.text(GAME_WIDTH / 2, 310, 'No two dungeons tell the same story', {
      fontSize: '12px',
      fontFamily: 'monospace',
      color: '#999999',
      fontStyle: 'italic'
    }).setOrigin(0.5);
    this.menuElements.push(tagline);

    // AI note
    const aiNote = this.add.text(GAME_WIDTH / 2, 332, 'Quests and story arcs are generated by AI. No two runs play the same.', {
      fontSize: '9px',
      fontFamily: 'monospace',
      color: '#666666'
    }).setOrigin(0.5);
    this.menuElements.push(aiNote);

    // Buttons
    const btnY = 380;
    const newGameBtn = this.createMenuButton(GAME_WIDTH / 2 - 100, btnY, '[ NEW GAME ]', () => this.startGame());
    const loadGameBtn = this.createMenuButton(GAME_WIDTH / 2 + 100, btnY, '[ LOAD GAME ]', () => this.showLoadMenu());
    this.menuElements.push(newGameBtn, loadGameBtn);

    // Gentle title bob
    this.tweens.add({
      targets: title,
      y: title.y - 3,
      duration: 2000,
      ease: 'Sine.easeInOut',
      yoyo: true,
      repeat: -1
    });

    // Controls section
    const controlsY = 430;
    const controlsTitle = this.add.text(GAME_WIDTH / 2, controlsY, 'Controls', {
      fontSize: '12px',
      fontFamily: 'monospace',
      color: '#888888'
    }).setOrigin(0.5);
    this.menuElements.push(controlsTitle);

    const controlLines = [
      'WASD / Arrows - Move     SPACE - Attack (hold to charge)     SHIFT - Dodge',
      'ENTER - Cast Spell       E - Interact / Open Chests          I - Inventory',
      'Q - Quest Log            M - Dungeon Map                     L - Stats / Level Up',
      'TAB - Cycle Overlays     ESC - Close                         F5 - Quick Save',
    ];

    controlLines.forEach((line, i) => {
      const text = this.add.text(GAME_WIDTH / 2, controlsY + 20 + i * 16, line, {
        fontSize: '9px',
        fontFamily: 'monospace',
        color: '#555555'
      }).setOrigin(0.5);
      this.menuElements.push(text);
    });

    // Gamepad note
    const gamepadNote = this.add.text(GAME_WIDTH / 2, controlsY + 20 + controlLines.length * 16 + 8, 'Gamepad: A=Attack  B=Dodge  X=Interact  Y=Inventory', {
      fontSize: '9px',
      fontFamily: 'monospace',
      color: '#444444'
    }).setOrigin(0.5);
    this.menuElements.push(gamepadNote);

    // Save list container (hidden initially)
    this.saveListContainer = this.add.container(0, 0);
    this.saveListContainer.setVisible(false);
  }

  private createMenuButton(x: number, y: number, label: string, callback: () => void): Phaser.GameObjects.Text {
    const btn = this.add.text(x, y, label, {
      fontSize: '18px',
      fontFamily: 'monospace',
      color: '#ffffff',
      backgroundColor: '#4a4a6a',
      padding: { x: 16, y: 6 }
    }).setOrigin(0.5).setInteractive({ useHandCursor: true });

    btn.on('pointerover', () => btn.setStyle({ color: '#c9a227' }));
    btn.on('pointerout', () => btn.setStyle({ color: '#ffffff' }));
    btn.on('pointerdown', callback);
    return btn;
  }

  private async showLoadMenu(): Promise<void> {
    if (this.showingSaves) return;
    this.showingSaves = true;
    this.saveListContainer.removeAll(true);
    this.saveListContainer.setVisible(true);

    // Overlay background
    const bg = this.add.rectangle(GAME_WIDTH / 2, GAME_HEIGHT / 2, 500, 350, 0x1a1a2e, 0.95);
    bg.setStrokeStyle(2, 0x4a4a6a);
    this.saveListContainer.add(bg);

    const titleText = this.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2 - 150, 'SAVED GAMES', {
      fontSize: '18px',
      fontFamily: 'monospace',
      color: '#c9a227'
    }).setOrigin(0.5);
    this.saveListContainer.add(titleText);

    // Close button
    const closeBtn = this.add.text(GAME_WIDTH / 2 + 220, GAME_HEIGHT / 2 - 155, 'X', {
      fontSize: '18px',
      fontFamily: 'monospace',
      color: '#ff6666'
    }).setOrigin(0.5).setInteractive({ useHandCursor: true });
    closeBtn.on('pointerdown', () => this.hideLoadMenu());
    this.saveListContainer.add(closeBtn);

    try {
      const saves = await listSaves();
      if (saves.length === 0) {
        const noSaves = this.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2, 'No saved games found', {
          fontSize: '14px',
          fontFamily: 'monospace',
          color: '#888888'
        }).setOrigin(0.5);
        this.saveListContainer.add(noSaves);
      } else {
        saves.slice(0, 5).forEach((save, index) => {
          this.createSaveEntry(save, index);
        });
      }
    } catch {
      const errText = this.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2, 'Could not connect to server', {
        fontSize: '14px',
        fontFamily: 'monospace',
        color: '#ff6666'
      }).setOrigin(0.5);
      this.saveListContainer.add(errText);
    }

    this.input.keyboard?.once('keydown-ESC', () => this.hideLoadMenu());
  }

  private createSaveEntry(save: SaveListItem, index: number): void {
    const y = GAME_HEIGHT / 2 - 100 + index * 50;
    const date = new Date(save.updatedAt).toLocaleString();

    const entryBg = this.add.rectangle(GAME_WIDTH / 2, y, 450, 40, 0x3a3a5a);
    entryBg.setInteractive({ useHandCursor: true });
    this.saveListContainer.add(entryBg);

    const nameText = this.add.text(GAME_WIDTH / 2 - 200, y, `${save.playerName}`, {
      fontSize: '13px',
      fontFamily: 'monospace',
      color: '#ffffff'
    }).setOrigin(0, 0.5);
    this.saveListContainer.add(nameText);

    const dateText = this.add.text(GAME_WIDTH / 2 + 50, y, date, {
      fontSize: '10px',
      fontFamily: 'monospace',
      color: '#888888'
    }).setOrigin(0, 0.5);
    this.saveListContainer.add(dateText);

    // Load on click
    entryBg.on('pointerover', () => entryBg.setFillStyle(0x5a5a7a));
    entryBg.on('pointerout', () => entryBg.setFillStyle(0x3a3a5a));
    entryBg.on('pointerdown', () => this.loadSave(save.id));

    // Delete button
    const delBtn = this.add.text(GAME_WIDTH / 2 + 200, y, 'X', {
      fontSize: '14px',
      fontFamily: 'monospace',
      color: '#ff6666'
    }).setOrigin(0.5).setInteractive({ useHandCursor: true });
    delBtn.on('pointerdown', async (pointer: Phaser.Input.Pointer) => {
      pointer.event.stopPropagation();
      await deleteGame(save.id);
      this.hideLoadMenu();
      this.showLoadMenu();
    });
    this.saveListContainer.add(delBtn);
  }

  private async loadSave(id: string): Promise<void> {
    try {
      const save = await loadGame(id);
      this.scene.start(SCENE_KEYS.GAME, { loadedSave: save });
      this.scene.start(SCENE_KEYS.UI);
    } catch (err) {
      console.error('Failed to load save:', err);
    }
  }

  private hideLoadMenu(): void {
    this.showingSaves = false;
    this.saveListContainer.removeAll(true);
    this.saveListContainer.setVisible(false);
  }

  private startGame(): void {
    this.showLoadingScreen();
    this.fetchIntroAndStart();
  }

  private showLoadingScreen(): void {
    // Hide menu elements
    this.menuElements.forEach(el => {
      if ('setVisible' in el) (el as unknown as { setVisible(v: boolean): void }).setVisible(false);
    });
    this.saveListContainer.setVisible(false);

    // Loading background
    this.cameras.main.setBackgroundColor('#0d0d1a');

    // Loading text
    this.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2 - 20, 'Preparing your adventure...', {
      fontSize: '18px',
      fontFamily: 'monospace',
      color: '#cc88ff',
      fontStyle: 'italic'
    }).setOrigin(0.5);

    // Animated dots
    const dots = this.add.text(GAME_WIDTH / 2, GAME_HEIGHT / 2 + 20, '.', {
      fontSize: '24px',
      fontFamily: 'monospace',
      color: '#888888'
    }).setOrigin(0.5);

    let dotCount = 1;
    this.time.addEvent({
      delay: 400,
      loop: true,
      callback: () => {
        dotCount = (dotCount % 3) + 1;
        dots.setText('.'.repeat(dotCount));
      }
    });
  }

  private fetchIntroAndStart(): void {
    console.log('[MenuScene] Requesting fresh intro narration...');

    regenerateIntro().then(intro => {
      if (intro && intro.length > 0) {
        console.log('[MenuScene] Intro received: %d lines', intro.length);
        this.scene.start(SCENE_KEYS.GAME, { introLines: intro });
      } else {
        console.log('[MenuScene] No intro returned, starting game without intro');
        this.scene.start(SCENE_KEYS.GAME);
      }
      this.scene.start(SCENE_KEYS.UI);
    }).catch(err => {
      console.log('[MenuScene] Intro fetch failed:', err);
      this.scene.start(SCENE_KEYS.GAME);
      this.scene.start(SCENE_KEYS.UI);
    });
  }
}
